"""Authored valuation catalog definitions.

Kept by domain so catalog content remains reviewable without changing its
canonical structure.
"""

from __future__ import annotations

from typing import Any

def _operand_decl(operand_id: str, *, unit_family: str, requiredness: str = "required", allowed_sign: str = "signed", claim_rule: str | None = None, period_rule: str | None = None) -> dict[str, Any]:
    decl: dict[str, Any] = {
        "operand_id": operand_id,
        "requiredness": requiredness,
        "unit_family": unit_family,
        "allowed_sign": allowed_sign,
    }
    if claim_rule is not None:
        decl["claim_rule"] = claim_rule
    if period_rule is not None:
        decl["period_rule"] = period_rule
    return decl


def _guard_step(guard_type: str, *, target_symbol: str | None = None, **extra: Any) -> dict[str, Any]:
    step: dict[str, Any] = {"guard_type": guard_type}
    if target_symbol is not None:
        step["target_symbol"] = target_symbol
    step.update(extra)
    return step


def _method_formula_entry(
    *,
    formula_id: str,
    method_id: str,
    label: str,
    economic_family_id: str,
    variant_dimensions: dict[str, Any],
    numerator_symbol: str,
    denominator_symbol: str,
    operand_declarations: list[dict[str, Any]],
    guard_plan: list[dict[str, Any]],
    output_unit: str,
    direction: str,
    claim_basis: str,
    per_share_or_aggregate: str,
    sign_policy: dict[str, Any],
    reason_mapping: list[dict[str, Any]],
    source_contract_refs: list[str],
) -> dict[str, Any]:
    return {
        "entry_id": formula_id,
        "entry_version": "1.0.0",
        "lifecycle_status": "approved",
        "label": label,
        "source_contract_refs": source_contract_refs,
        "body": {
            "method_id": method_id,
            "economic_family_id": economic_family_id,
            "variant_dimensions": variant_dimensions,
            "operand_declarations": operand_declarations,
            "guard_plan": guard_plan,
            "expression_ast": {
                "op": "divide",
                "numerator": {"op": "operand", "symbol": numerator_symbol},
                "denominator": {"op": "operand", "symbol": denominator_symbol},
            },
            "unit_equation": {
                "numerator_unit_family": "amount",
                "denominator_unit_family": "amount",
                "output_unit": output_unit,
            },
            "output_semantics": {
                "unit": output_unit,
                "direction_interpretation": direction,
                "claim_basis": claim_basis,
                "per_share_or_aggregate": per_share_or_aggregate,
                "display_policy_ref": "shared.policy.rounding_default",
                "arithmetic_context_ref": "val.numeric.context.method.v1",
            },
            "sign_policy": sign_policy,
            "arithmetic_context_ref": "val.numeric.context.method.v1",
            "display_policy_ref": "shared.policy.rounding_default",
            "reason_mapping": reason_mapping,
        },
    }


_METHOD_FORMULA_ENTRIES: list[dict[str, Any]] = [
    _method_formula_entry(
        formula_id="val.formula.method.pe.reported_parent",
        method_id="val.method.pe.reported_parent",
        label="P/E, reported parent earnings, true TTM or latest FY",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "true_ttm_or_fy"},
        numerator_symbol="market_cap", denominator_symbol="parent_net_income",
        operand_declarations=[
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("denominator_nonzero", target_symbol="parent_net_income"),
            _guard_step("denominator_positive", target_symbol="parent_net_income"),
            _guard_step("sign_constraint", target_symbol="market_cap", require="positive"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#4"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.earnings_yield.reported_parent",
        method_id="val.method.earnings_yield.reported_parent",
        label="Net-income earnings yield, reported parent, true TTM or latest FY",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "true_ttm_or_fy"},
        numerator_symbol="parent_net_income", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#5"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.pe.reported_parent_ttm",
        method_id="val.method.pe.reported_parent",
        label="P/E, reported parent earnings, true TTM",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "true_ttm"},
        numerator_symbol="market_cap", denominator_symbol="parent_net_income",
        operand_declarations=[
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity", period_rule="true_ttm"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("period_match", target_symbol="parent_net_income", required_period="true_ttm"),
            _guard_step("denominator_nonzero", target_symbol="parent_net_income"),
            _guard_step("denominator_positive", target_symbol="parent_net_income"),
            _guard_step("sign_constraint", target_symbol="market_cap", require="positive"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "period_match_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#4"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.pe.reported_parent_fy",
        method_id="val.method.pe.reported_parent",
        label="P/E, reported parent earnings, latest FY",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "fy"},
        numerator_symbol="market_cap", denominator_symbol="parent_net_income",
        operand_declarations=[
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity", period_rule="fy"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("period_match", target_symbol="parent_net_income", required_period="fy"),
            _guard_step("denominator_nonzero", target_symbol="parent_net_income"),
            _guard_step("denominator_positive", target_symbol="parent_net_income"),
            _guard_step("sign_constraint", target_symbol="market_cap", require="positive"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "period_match_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#4"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.earnings_yield.reported_parent_ttm",
        method_id="val.method.earnings_yield.reported_parent",
        label="Net-income earnings yield, reported parent, true TTM",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "true_ttm"},
        numerator_symbol="parent_net_income", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity", period_rule="true_ttm"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("period_match", target_symbol="parent_net_income", required_period="true_ttm"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "period_match_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#5"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.earnings_yield.reported_parent_fy",
        method_id="val.method.earnings_yield.reported_parent",
        label="Net-income earnings yield, reported parent, latest FY",
        economic_family_id="val.family.parent_earnings_valuation",
        variant_dimensions={"period_variant": "fy"},
        numerator_symbol="parent_net_income", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("parent_net_income", unit_family="amount", claim_rule="parent_common_equity", period_rule="fy"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="parent_net_income"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("claim_match", target_symbol="parent_net_income", against_symbol="market_cap"),
            _guard_step("period_match", target_symbol="parent_net_income", required_period="fy"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "period_match_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#5"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.price_to_book.parent_equity",
        method_id="val.method.price_to_book.parent_equity",
        label="P/B, parent equity",
        economic_family_id="val.family.parent_book_valuation",
        variant_dimensions={"period_variant": "spot"},
        numerator_symbol="market_cap", denominator_symbol="parent_equity",
        operand_declarations=[
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
            _operand_decl("parent_equity", unit_family="amount", claim_rule="parent_common_equity", period_rule="spot"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("required_available", target_symbol="parent_equity"),
            _guard_step("claim_match", target_symbol="parent_equity", against_symbol="market_cap"),
            _guard_step("period_match", target_symbol="parent_equity", required_period="spot"),
            _guard_step("accounting_match", target_symbol="parent_equity"),
            _guard_step("denominator_nonzero", target_symbol="parent_equity"),
            _guard_step("denominator_positive", target_symbol="parent_equity"),
            _guard_step("sign_constraint", target_symbol="market_cap", require="positive"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#6"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.fcf_yield.standard_equity",
        method_id="val.method.fcf_yield.standard_equity",
        label="Standard FCF yield, equity (parent-attributed via net-income share)",
        economic_family_id="val.family.equity_free_cash_flow_yield",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "fcf_basis": "standard_parent_share"},
        numerator_symbol="standard_fcf_parent_share", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("standard_fcf_parent_share", unit_family="amount", claim_rule="parent_equity_cash_proxy_ni_attributed"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="standard_fcf_parent_share"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_equity_cash_proxy_ni_attributed", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.cash_flow_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#7", "wiki/systems/valuation-pipeline.md#serbest-nakit-akışı-yönteminin-nci-atfı-2026-07-22"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.fcf_yield.after_lease_equity",
        method_id="val.method.fcf_yield.after_lease_equity",
        label="After-lease FCF yield, equity (parent-attributed via net-income share)",
        economic_family_id="val.family.equity_free_cash_flow_yield",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "fcf_basis": "after_lease_parent_share"},
        numerator_symbol="after_lease_fcf_parent_share", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("after_lease_fcf_parent_share", unit_family="amount", claim_rule="parent_equity_cash_proxy_ni_attributed"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="after_lease_fcf_parent_share"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("capability_required", target_symbol="after_lease_fcf_parent_share", capability_id="lease.principal.classification.complete"),
            _guard_step("reconciliation_required", target_symbol="after_lease_fcf_parent_share", rule="no_cfo_lease_double_subtraction"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_equity_cash_proxy_ni_attributed", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.lease_basis_mismatch"},
            {"condition": "capability_required_failed", "status": "unavailable", "reason_code": "method.lease_basis_mismatch"},
            {"condition": "reconciliation_required_failed", "status": "calculation_blocked", "reason_code": "method.lease_basis_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#8", "wiki/systems/valuation-pipeline.md#serbest-nakit-akışı-yönteminin-nci-atfı-2026-07-22"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.fcfe_yield",
        method_id="val.method.fcfe_yield",
        label="FCFE yield extension",
        economic_family_id="val.family.equity_free_cash_flow_yield",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "fcf_basis": "fcfe"},
        numerator_symbol="fcfe", denominator_symbol="market_cap",
        operand_declarations=[
            _operand_decl("fcfe", unit_family="amount", claim_rule="parent_common_equity"),
            _operand_decl("market_cap", unit_family="amount", allowed_sign="positive", claim_rule="parent_common_equity"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="fcfe"),
            _guard_step("required_available", target_symbol="market_cap"),
            _guard_step("capability_required", target_symbol="fcfe", capability_id="capital.fcfe_bridge.complete"),
            _guard_step("denominator_nonzero", target_symbol="market_cap"),
            _guard_step("denominator_positive", target_symbol="market_cap"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="parent_common_equity", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": True},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.cash_flow_claim_mismatch"},
            {"condition": "capability_required_failed", "status": "unavailable", "reason_code": "method.cash_flow_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#9"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.ev_to_ebit.core",
        method_id="val.method.ev_to_ebit.core",
        label="EV/EBIT, core",
        economic_family_id="val.family.enterprise_core_operating_earnings",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "ev_basis": "lease_exclusive"},
        numerator_symbol="enterprise_value_ex_lease", denominator_symbol="core_ebit",
        operand_declarations=[
            _operand_decl("enterprise_value_ex_lease", unit_family="amount", allowed_sign="positive", claim_rule="enterprise_consolidated"),
            _operand_decl("core_ebit", unit_family="amount", claim_rule="enterprise_consolidated"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="enterprise_value_ex_lease"),
            _guard_step("required_available", target_symbol="core_ebit"),
            _guard_step("claim_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("currency_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("scale_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("denominator_nonzero", target_symbol="core_ebit"),
            _guard_step("denominator_positive", target_symbol="core_ebit"),
            _guard_step("sign_constraint", target_symbol="enterprise_value_ex_lease", require="positive"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="enterprise_consolidated", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
            {"condition": "sign_constraint_failed", "status": "not_meaningful", "reason_code": "method.enterprise_value_nonpositive"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#10"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.ebit_yield.core",
        method_id="val.method.ebit_yield.core",
        label="EBIT/EV, core",
        economic_family_id="val.family.enterprise_core_operating_earnings",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "ev_basis": "lease_exclusive"},
        numerator_symbol="core_ebit", denominator_symbol="enterprise_value_ex_lease",
        operand_declarations=[
            _operand_decl("core_ebit", unit_family="amount", claim_rule="enterprise_consolidated"),
            _operand_decl("enterprise_value_ex_lease", unit_family="amount", allowed_sign="positive", claim_rule="enterprise_consolidated"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="core_ebit"),
            _guard_step("required_available", target_symbol="enterprise_value_ex_lease"),
            _guard_step("claim_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("currency_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("scale_match", target_symbol="core_ebit", against_symbol="enterprise_value_ex_lease"),
            _guard_step("denominator_nonzero", target_symbol="enterprise_value_ex_lease"),
            _guard_step("denominator_positive", target_symbol="enterprise_value_ex_lease"),
            _guard_step("sign_constraint", target_symbol="core_ebit", require="positive"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="enterprise_consolidated", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.period_basis_unavailable"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.enterprise_value_nonpositive"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#11"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.ev_to_ebitda.canonical",
        method_id="val.method.ev_to_ebitda.canonical",
        label="EV/EBITDA, canonical",
        economic_family_id="val.family.enterprise_ebitda",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "ev_basis": "lease_exclusive"},
        numerator_symbol="enterprise_value_ex_lease", denominator_symbol="canonical_ebitda",
        operand_declarations=[
            _operand_decl("enterprise_value_ex_lease", unit_family="amount", allowed_sign="positive", claim_rule="enterprise_consolidated"),
            _operand_decl("canonical_ebitda", unit_family="amount", claim_rule="enterprise_consolidated"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="enterprise_value_ex_lease"),
            _guard_step("required_available", target_symbol="canonical_ebitda"),
            _guard_step("capability_required", target_symbol="canonical_ebitda", capability_id="metric.canonical_ebitda.available"),
            _guard_step("reconciliation_required", target_symbol="canonical_ebitda", rule="no_reported_vs_constructed_candidate_conflict"),
            _guard_step("denominator_nonzero", target_symbol="canonical_ebitda"),
            _guard_step("denominator_positive", target_symbol="canonical_ebitda"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="enterprise_consolidated", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.canonical_ebitda_unavailable"},
            {"condition": "capability_required_failed", "status": "unavailable", "reason_code": "method.canonical_ebitda_unavailable"},
            {"condition": "reconciliation_required_failed", "status": "calculation_blocked", "reason_code": "method.canonical_ebitda_unavailable"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#12"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.ev_to_ebitdar.aviation_lease_inclusive",
        method_id="val.method.ev_to_ebitdar.aviation_lease_inclusive",
        label="EV/EBITDAR, aviation lease-inclusive",
        economic_family_id="val.family.aviation_ebitdar",
        variant_dimensions={"period_variant": "true_ttm_or_fy", "ev_basis": "lease_inclusive"},
        numerator_symbol="enterprise_value_incl_lease", denominator_symbol="canonical_ebitdar",
        operand_declarations=[
            _operand_decl("enterprise_value_incl_lease", unit_family="amount", allowed_sign="positive", claim_rule="enterprise_consolidated"),
            _operand_decl("canonical_ebitdar", unit_family="amount", claim_rule="enterprise_consolidated"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="enterprise_value_incl_lease"),
            _guard_step("required_available", target_symbol="canonical_ebitdar"),
            _guard_step("capability_required", target_symbol="enterprise_value_incl_lease", capability_id="capital.ev.lease_inclusive.available"),
            _guard_step("capability_required", target_symbol="canonical_ebitdar", capability_id="metric.canonical_aviation_ebitdar.available"),
            _guard_step("reconciliation_required", target_symbol="canonical_ebitdar", rule="rent_lease_fleet_reconciliation_passed"),
            _guard_step("currency_match", target_symbol="canonical_ebitdar", against_symbol="enterprise_value_incl_lease"),
            _guard_step("period_match", target_symbol="canonical_ebitdar", required_period="true_ttm_or_fy"),
            _guard_step("denominator_nonzero", target_symbol="canonical_ebitdar"),
            _guard_step("denominator_positive", target_symbol="canonical_ebitdar"),
        ],
        output_unit="multiple", direction="lower_is_more_attractive",
        claim_basis="enterprise_consolidated", per_share_or_aggregate="aggregate",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.lease_basis_mismatch"},
            {"condition": "capability_required_failed", "status": "unavailable", "reason_code": "method.lease_basis_mismatch"},
            {"condition": "reconciliation_required_failed", "status": "calculation_blocked", "reason_code": "method.ebitdar_reconciliation_failed"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#13"],
    ),
    _method_formula_entry(
        formula_id="val.formula.method.dividend_yield.cash_declared_paid",
        method_id="val.method.dividend_yield.cash_declared_paid",
        label="Dividend yield, cash declared/paid",
        economic_family_id="val.family.dividend_distribution_yield",
        variant_dimensions={"period_variant": "trailing_12m_event"},
        numerator_symbol="dividend_per_share", denominator_symbol="spot_price_per_share",
        operand_declarations=[
            _operand_decl("dividend_per_share", unit_family="price_per_share", allowed_sign="nonnegative"),
            _operand_decl("spot_price_per_share", unit_family="price_per_share", allowed_sign="positive"),
        ],
        guard_plan=[
            _guard_step("required_available", target_symbol="dividend_per_share"),
            _guard_step("required_available", target_symbol="spot_price_per_share"),
            _guard_step("claim_match", target_symbol="dividend_per_share", against_symbol="spot_price_per_share"),
            _guard_step("denominator_nonzero", target_symbol="spot_price_per_share"),
            _guard_step("denominator_positive", target_symbol="spot_price_per_share"),
        ],
        output_unit="ratio", direction="higher_is_more_attractive",
        claim_basis="common_share_current_equivalent", per_share_or_aggregate="per_share",
        sign_policy={"zero_denominator": "not_meaningful", "negative_denominator": "not_meaningful", "negative_numerator_diagnostic_allowed": False},
        reason_mapping=[
            {"condition": "required_available_failed", "status": "unavailable", "reason_code": "method.dividend_event_missing"},
            {"condition": "claim_match_failed", "status": "calculation_blocked", "reason_code": "method.parent_claim_mismatch"},
            {"condition": "denominator_zero", "status": "not_meaningful", "reason_code": "method.denominator_zero"},
            {"condition": "denominator_negative", "status": "not_meaningful", "reason_code": "method.denominator_negative"},
        ],
        source_contract_refs=["docs/valuation-t67-03-valuation-method-formula-catalog.md#14"],
    ),
]
